language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-akta-markup' ]; then cd .. && eval "mv $currentfolder generator-akta-markup" && cd generator-akta-markup; fi

